### PR TITLE
Display Carousel UI on Auto Layout tab

### PR DESCRIPTION
**Pull request by wsu-nyt**
Adds an Auto Layout based Carousel UI.

Screen Shot 2020-09-08 at 1 51 16 PM

### CODE REVIEW

**Comment by ZevEisenberg** [comment]
This uses a collection view in a cell. @wsu-nyt and I were wondering whether we should use compositional layout for better performance (but only one iOS 13+), or should we stick with the current approach to more closely match newsreader?

**Comment by wsu-nyt** [comment]
PR https://github.com/JonLz/adk_experiment/pull/4 demonstrates how compositional layout helps us to build carousel UI. From developer experience’s perspective, compositional layout reduces the complexity of view hierarchy as we no longer to build a nested collection view.

I wonder if there’s a way we can check the current OS adoption rate?

**Comment by ZevEisenberg** [comment]
There may be, but there are already plans to drop iOS 12 relatively soon-ish, I believe. I think this test should be future-looking, so we should be ok with 13+.

**Comment by wsu-nyt** [comment]
Got it thanks! I guess we can close this PR then.

**Pull request closed without merging**
